name: 'Build and Test'
description: 'Build the project sources and run all unit tests'
inputs:
  configuration:
    description: 'CMake build configuration'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.configuration }}