ARG BASE_TAG=22.04
FROM ubuntu:${BASE_TAG} as build-stage
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    autoconf \
    cmake \
    g++ \
    gcc \
    libtool \
    make \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
ARG PROTOBUF_VERSION=21.0
RUN wget -O protobuf-cpp-"${PROTOBUF_VERSION}".tar.gz \
    https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protobuf-cpp-3.${PROTOBUF_VERSION}.tar.gz \
    && tar -xzf protobuf-cpp-"${PROTOBUF_VERSION}".tar.gz \
    && rm protobuf-cpp-"${PROTOBUF_VERSION}".tar.gz

WORKDIR /tmp/protobuf-3."${PROTOBUF_VERSION}"
RUN ./autogen.sh \
    && ./configure \
    && make \
    && make install


FROM ubuntu:${BASE_TAG} as google-dependencies
COPY --from=build-stage /usr/local/include/google /usr/local/include/google
COPY --from=build-stage /usr/local/lib/libproto* /usr/local/lib/
COPY --from=build-stage /usr/local/bin/protoc /usr/local/bin
RUN ldconfig
