// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state_representation/space/spatial_state.proto

#include "state_representation/space/spatial_state.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace state_representation {
namespace proto {
constexpr SpatialState::SpatialState(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : reference_frame_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , state_(nullptr){}
struct SpatialStateDefaultTypeInternal {
  constexpr SpatialStateDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SpatialStateDefaultTypeInternal() {}
  union {
    SpatialState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SpatialStateDefaultTypeInternal _SpatialState_default_instance_;
}  // namespace proto
}  // namespace state_representation
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::state_representation::proto::SpatialState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::state_representation::proto::SpatialState, state_),
  PROTOBUF_FIELD_OFFSET(::state_representation::proto::SpatialState, reference_frame_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::state_representation::proto::SpatialState)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::state_representation::proto::_SpatialState_default_instance_),
};

const char descriptor_table_protodef_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n.state_representation/space/spatial_sta"
  "te.proto\022\032state_representation.proto\032 st"
  "ate_representation/state.proto\"Y\n\014Spatia"
  "lState\0220\n\005state\030\001 \001(\0132!.state_representa"
  "tion.proto.State\022\027\n\017reference_frame\030\002 \001("
  "\tb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto_deps[1] = {
  &::descriptor_table_state_5frepresentation_2fstate_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto = {
  false, false, 209, descriptor_table_protodef_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto, "state_representation/space/spatial_state.proto", 
  &descriptor_table_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto_once, descriptor_table_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto::offsets,
  file_level_metadata_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto, file_level_enum_descriptors_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto, file_level_service_descriptors_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto_getter() {
  return &descriptor_table_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto(&descriptor_table_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto);
namespace state_representation {
namespace proto {

// ===================================================================

class SpatialState::_Internal {
 public:
  static const ::state_representation::proto::State& state(const SpatialState* msg);
};

const ::state_representation::proto::State&
SpatialState::_Internal::state(const SpatialState* msg) {
  return *msg->state_;
}
void SpatialState::clear_state() {
  if (GetArenaForAllocation() == nullptr && state_ != nullptr) {
    delete state_;
  }
  state_ = nullptr;
}
SpatialState::SpatialState(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:state_representation.proto.SpatialState)
}
SpatialState::SpatialState(const SpatialState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  reference_frame_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_reference_frame().empty()) {
    reference_frame_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_reference_frame(), 
      GetArenaForAllocation());
  }
  if (from._internal_has_state()) {
    state_ = new ::state_representation::proto::State(*from.state_);
  } else {
    state_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:state_representation.proto.SpatialState)
}

void SpatialState::SharedCtor() {
reference_frame_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
state_ = nullptr;
}

SpatialState::~SpatialState() {
  // @@protoc_insertion_point(destructor:state_representation.proto.SpatialState)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SpatialState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  reference_frame_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete state_;
}

void SpatialState::ArenaDtor(void* object) {
  SpatialState* _this = reinterpret_cast< SpatialState* >(object);
  (void)_this;
}
void SpatialState::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SpatialState::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SpatialState::Clear() {
// @@protoc_insertion_point(message_clear_start:state_representation.proto.SpatialState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  reference_frame_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && state_ != nullptr) {
    delete state_;
  }
  state_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SpatialState::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .state_representation.proto.State state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_state(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string reference_frame = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_reference_frame();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "state_representation.proto.SpatialState.reference_frame"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SpatialState::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:state_representation.proto.SpatialState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .state_representation.proto.State state = 1;
  if (this->has_state()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::state(this), target, stream);
  }

  // string reference_frame = 2;
  if (!this->reference_frame().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reference_frame().data(), static_cast<int>(this->_internal_reference_frame().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "state_representation.proto.SpatialState.reference_frame");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_reference_frame(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:state_representation.proto.SpatialState)
  return target;
}

size_t SpatialState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:state_representation.proto.SpatialState)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string reference_frame = 2;
  if (!this->reference_frame().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_reference_frame());
  }

  // .state_representation.proto.State state = 1;
  if (this->has_state()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *state_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SpatialState::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:state_representation.proto.SpatialState)
  GOOGLE_DCHECK_NE(&from, this);
  const SpatialState* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SpatialState>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:state_representation.proto.SpatialState)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:state_representation.proto.SpatialState)
    MergeFrom(*source);
  }
}

void SpatialState::MergeFrom(const SpatialState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:state_representation.proto.SpatialState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from.reference_frame().empty()) {
    _internal_set_reference_frame(from._internal_reference_frame());
  }
  if (from.has_state()) {
    _internal_mutable_state()->::state_representation::proto::State::MergeFrom(from._internal_state());
  }
}

void SpatialState::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:state_representation.proto.SpatialState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpatialState::CopyFrom(const SpatialState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:state_representation.proto.SpatialState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpatialState::IsInitialized() const {
  return true;
}

void SpatialState::InternalSwap(SpatialState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &reference_frame_, GetArenaForAllocation(),
      &other->reference_frame_, other->GetArenaForAllocation()
  );
  swap(state_, other->state_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SpatialState::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto_getter, &descriptor_table_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto_once,
      file_level_metadata_state_5frepresentation_2fspace_2fspatial_5fstate_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace state_representation
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::state_representation::proto::SpatialState* Arena::CreateMaybeMessage< ::state_representation::proto::SpatialState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::state_representation::proto::SpatialState >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
