# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state_representation/state_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from state_representation import state_pb2 as state__representation_dot_state__pb2
from state_representation.space import spatial_state_pb2 as state__representation_dot_space_dot_spatial__state__pb2
from state_representation.space.cartesian import cartesian_state_pb2 as state__representation_dot_space_dot_cartesian_dot_cartesian__state__pb2
from state_representation.space.joint import jacobian_pb2 as state__representation_dot_space_dot_joint_dot_jacobian__pb2
from state_representation.space.joint import joint_state_pb2 as state__representation_dot_space_dot_joint_dot_joint__state__pb2
from state_representation.geometry import shape_pb2 as state__representation_dot_geometry_dot_shape__pb2
from state_representation.geometry import ellipsoid_pb2 as state__representation_dot_geometry_dot_ellipsoid__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='state_representation/state_message.proto',
  package='state_representation.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(state_representation/state_message.proto\x12\x1astate_representation.proto\x1a state_representation/state.proto\x1a.state_representation/space/spatial_state.proto\x1a:state_representation/space/cartesian/cartesian_state.proto\x1a/state_representation/space/joint/jacobian.proto\x1a\x32state_representation/space/joint/joint_state.proto\x1a)state_representation/geometry/shape.proto\x1a-state_representation/geometry/ellipsoid.proto\"\xed\x06\n\x0cStateMessage\x12\x32\n\x05state\x18\x01 \x01(\x0b\x32!.state_representation.proto.StateH\x00\x12\x41\n\rspatial_state\x18\x02 \x01(\x0b\x32(.state_representation.proto.SpatialStateH\x00\x12\x45\n\x0f\x63\x61rtesian_state\x18\x03 \x01(\x0b\x32*.state_representation.proto.CartesianStateH\x00\x12\x43\n\x0e\x63\x61rtesian_pose\x18\x04 \x01(\x0b\x32).state_representation.proto.CartesianPoseH\x00\x12\x45\n\x0f\x63\x61rtesian_twist\x18\x05 \x01(\x0b\x32*.state_representation.proto.CartesianTwistH\x00\x12G\n\x10\x63\x61rtesian_wrench\x18\x06 \x01(\x0b\x32+.state_representation.proto.CartesianWrenchH\x00\x12\x38\n\x08jacobian\x18\x07 \x01(\x0b\x32$.state_representation.proto.JacobianH\x00\x12=\n\x0bjoint_state\x18\x08 \x01(\x0b\x32&.state_representation.proto.JointStateH\x00\x12\x45\n\x0fjoint_positions\x18\t \x01(\x0b\x32*.state_representation.proto.JointPositionsH\x00\x12G\n\x10joint_velocities\x18\n \x01(\x0b\x32+.state_representation.proto.JointVelocitiesH\x00\x12\x41\n\rjoint_torques\x18\x0b \x01(\x0b\x32(.state_representation.proto.JointTorquesH\x00\x12\x32\n\x05shape\x18\x0c \x01(\x0b\x32!.state_representation.proto.ShapeH\x00\x12:\n\tellipsoid\x18\r \x01(\x0b\x32%.state_representation.proto.EllipsoidH\x00\x42\x0e\n\x0cmessage_typeb\x06proto3'
  ,
  dependencies=[state__representation_dot_state__pb2.DESCRIPTOR,state__representation_dot_space_dot_spatial__state__pb2.DESCRIPTOR,state__representation_dot_space_dot_cartesian_dot_cartesian__state__pb2.DESCRIPTOR,state__representation_dot_space_dot_joint_dot_jacobian__pb2.DESCRIPTOR,state__representation_dot_space_dot_joint_dot_joint__state__pb2.DESCRIPTOR,state__representation_dot_geometry_dot_shape__pb2.DESCRIPTOR,state__representation_dot_geometry_dot_ellipsoid__pb2.DESCRIPTOR,])




_STATEMESSAGE = _descriptor.Descriptor(
  name='StateMessage',
  full_name='state_representation.proto.StateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='state_representation.proto.StateMessage.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spatial_state', full_name='state_representation.proto.StateMessage.spatial_state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cartesian_state', full_name='state_representation.proto.StateMessage.cartesian_state', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cartesian_pose', full_name='state_representation.proto.StateMessage.cartesian_pose', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cartesian_twist', full_name='state_representation.proto.StateMessage.cartesian_twist', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cartesian_wrench', full_name='state_representation.proto.StateMessage.cartesian_wrench', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jacobian', full_name='state_representation.proto.StateMessage.jacobian', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joint_state', full_name='state_representation.proto.StateMessage.joint_state', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joint_positions', full_name='state_representation.proto.StateMessage.joint_positions', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joint_velocities', full_name='state_representation.proto.StateMessage.joint_velocities', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joint_torques', full_name='state_representation.proto.StateMessage.joint_torques', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shape', full_name='state_representation.proto.StateMessage.shape', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ellipsoid', full_name='state_representation.proto.StateMessage.ellipsoid', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message_type', full_name='state_representation.proto.StateMessage.message_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=406,
  serialized_end=1283,
)

_STATEMESSAGE.fields_by_name['state'].message_type = state__representation_dot_state__pb2._STATE
_STATEMESSAGE.fields_by_name['spatial_state'].message_type = state__representation_dot_space_dot_spatial__state__pb2._SPATIALSTATE
_STATEMESSAGE.fields_by_name['cartesian_state'].message_type = state__representation_dot_space_dot_cartesian_dot_cartesian__state__pb2._CARTESIANSTATE
_STATEMESSAGE.fields_by_name['cartesian_pose'].message_type = state__representation_dot_space_dot_cartesian_dot_cartesian__state__pb2._CARTESIANPOSE
_STATEMESSAGE.fields_by_name['cartesian_twist'].message_type = state__representation_dot_space_dot_cartesian_dot_cartesian__state__pb2._CARTESIANTWIST
_STATEMESSAGE.fields_by_name['cartesian_wrench'].message_type = state__representation_dot_space_dot_cartesian_dot_cartesian__state__pb2._CARTESIANWRENCH
_STATEMESSAGE.fields_by_name['jacobian'].message_type = state__representation_dot_space_dot_joint_dot_jacobian__pb2._JACOBIAN
_STATEMESSAGE.fields_by_name['joint_state'].message_type = state__representation_dot_space_dot_joint_dot_joint__state__pb2._JOINTSTATE
_STATEMESSAGE.fields_by_name['joint_positions'].message_type = state__representation_dot_space_dot_joint_dot_joint__state__pb2._JOINTPOSITIONS
_STATEMESSAGE.fields_by_name['joint_velocities'].message_type = state__representation_dot_space_dot_joint_dot_joint__state__pb2._JOINTVELOCITIES
_STATEMESSAGE.fields_by_name['joint_torques'].message_type = state__representation_dot_space_dot_joint_dot_joint__state__pb2._JOINTTORQUES
_STATEMESSAGE.fields_by_name['shape'].message_type = state__representation_dot_geometry_dot_shape__pb2._SHAPE
_STATEMESSAGE.fields_by_name['ellipsoid'].message_type = state__representation_dot_geometry_dot_ellipsoid__pb2._ELLIPSOID
_STATEMESSAGE.oneofs_by_name['message_type'].fields.append(
  _STATEMESSAGE.fields_by_name['state'])
_STATEMESSAGE.fields_by_name['state'].containing_oneof = _STATEMESSAGE.oneofs_by_name['message_type']
_STATEMESSAGE.oneofs_by_name['message_type'].fields.append(
  _STATEMESSAGE.fields_by_name['spatial_state'])
_STATEMESSAGE.fields_by_name['spatial_state'].containing_oneof = _STATEMESSAGE.oneofs_by_name['message_type']
_STATEMESSAGE.oneofs_by_name['message_type'].fields.append(
  _STATEMESSAGE.fields_by_name['cartesian_state'])
_STATEMESSAGE.fields_by_name['cartesian_state'].containing_oneof = _STATEMESSAGE.oneofs_by_name['message_type']
_STATEMESSAGE.oneofs_by_name['message_type'].fields.append(
  _STATEMESSAGE.fields_by_name['cartesian_pose'])
_STATEMESSAGE.fields_by_name['cartesian_pose'].containing_oneof = _STATEMESSAGE.oneofs_by_name['message_type']
_STATEMESSAGE.oneofs_by_name['message_type'].fields.append(
  _STATEMESSAGE.fields_by_name['cartesian_twist'])
_STATEMESSAGE.fields_by_name['cartesian_twist'].containing_oneof = _STATEMESSAGE.oneofs_by_name['message_type']
_STATEMESSAGE.oneofs_by_name['message_type'].fields.append(
  _STATEMESSAGE.fields_by_name['cartesian_wrench'])
_STATEMESSAGE.fields_by_name['cartesian_wrench'].containing_oneof = _STATEMESSAGE.oneofs_by_name['message_type']
_STATEMESSAGE.oneofs_by_name['message_type'].fields.append(
  _STATEMESSAGE.fields_by_name['jacobian'])
_STATEMESSAGE.fields_by_name['jacobian'].containing_oneof = _STATEMESSAGE.oneofs_by_name['message_type']
_STATEMESSAGE.oneofs_by_name['message_type'].fields.append(
  _STATEMESSAGE.fields_by_name['joint_state'])
_STATEMESSAGE.fields_by_name['joint_state'].containing_oneof = _STATEMESSAGE.oneofs_by_name['message_type']
_STATEMESSAGE.oneofs_by_name['message_type'].fields.append(
  _STATEMESSAGE.fields_by_name['joint_positions'])
_STATEMESSAGE.fields_by_name['joint_positions'].containing_oneof = _STATEMESSAGE.oneofs_by_name['message_type']
_STATEMESSAGE.oneofs_by_name['message_type'].fields.append(
  _STATEMESSAGE.fields_by_name['joint_velocities'])
_STATEMESSAGE.fields_by_name['joint_velocities'].containing_oneof = _STATEMESSAGE.oneofs_by_name['message_type']
_STATEMESSAGE.oneofs_by_name['message_type'].fields.append(
  _STATEMESSAGE.fields_by_name['joint_torques'])
_STATEMESSAGE.fields_by_name['joint_torques'].containing_oneof = _STATEMESSAGE.oneofs_by_name['message_type']
_STATEMESSAGE.oneofs_by_name['message_type'].fields.append(
  _STATEMESSAGE.fields_by_name['shape'])
_STATEMESSAGE.fields_by_name['shape'].containing_oneof = _STATEMESSAGE.oneofs_by_name['message_type']
_STATEMESSAGE.oneofs_by_name['message_type'].fields.append(
  _STATEMESSAGE.fields_by_name['ellipsoid'])
_STATEMESSAGE.fields_by_name['ellipsoid'].containing_oneof = _STATEMESSAGE.oneofs_by_name['message_type']
DESCRIPTOR.message_types_by_name['StateMessage'] = _STATEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StateMessage = _reflection.GeneratedProtocolMessageType('StateMessage', (_message.Message,), {
  'DESCRIPTOR' : _STATEMESSAGE,
  '__module__' : 'state_representation.state_message_pb2'
  # @@protoc_insertion_point(class_scope:state_representation.proto.StateMessage)
  })
_sym_db.RegisterMessage(StateMessage)


# @@protoc_insertion_point(module_scope)
