# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state_representation/state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='state_representation/state.proto',
  package='state_representation.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n state_representation/state.proto\x12\x1astate_representation.proto\"l\n\x05State\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x33\n\x04type\x18\x02 \x01(\x0e\x32%.state_representation.proto.StateType\x12\r\n\x05\x65mpty\x18\x03 \x01(\x08\x12\x11\n\ttimestamp\x18\x04 \x01(\x03*\xed\x03\n\tStateType\x12\t\n\x05STATE\x10\x00\x12\x12\n\x0e\x43\x41RTESIANSTATE\x10\x01\x12\x17\n\x13\x44UALQUATERNIONSTATE\x10\x02\x12\x0e\n\nJOINTSTATE\x10\x03\x12\x12\n\x0eJACOBIANMATRIX\x10\x04\x12\x0e\n\nTRAJECTORY\x10\x05\x12\x12\n\x0eGEOMETRY_SHAPE\x10\x06\x12\x16\n\x12GEOMETRY_ELLIPSOID\x10\x07\x12\x14\n\x10PARAMETER_DOUBLE\x10\x08\x12\x1a\n\x16PARAMETER_DOUBLE_ARRAY\x10\t\x12\x12\n\x0ePARAMETER_BOOL\x10\n\x12\x18\n\x14PARAMETER_BOOL_ARRAY\x10\x0b\x12\x14\n\x10PARAMETER_STRING\x10\x0c\x12\x1a\n\x16PARAMETER_STRING_ARRAY\x10\r\x12\x1c\n\x18PARAMETER_CARTESIANSTATE\x10\x0e\x12\x1b\n\x17PARAMETER_CARTESIANPOSE\x10\x0f\x12\x18\n\x14PARAMETER_JOINTSTATE\x10\x10\x12\x1c\n\x18PARAMETER_JOINTPOSITIONS\x10\x11\x12\x17\n\x13PARAMETER_ELLIPSOID\x10\x12\x12\x14\n\x10PARAMETER_MATRIX\x10\x13\x12\x14\n\x10PARAMETER_VECTOR\x10\x14\x62\x06proto3'
)

_STATETYPE = _descriptor.EnumDescriptor(
  name='StateType',
  full_name='state_representation.proto.StateType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CARTESIANSTATE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DUALQUATERNIONSTATE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JOINTSTATE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JACOBIANMATRIX', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRAJECTORY', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GEOMETRY_SHAPE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GEOMETRY_ELLIPSOID', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_DOUBLE', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_DOUBLE_ARRAY', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_BOOL', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_BOOL_ARRAY', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_STRING', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_STRING_ARRAY', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_CARTESIANSTATE', index=14, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_CARTESIANPOSE', index=15, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_JOINTSTATE', index=16, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_JOINTPOSITIONS', index=17, number=17,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_ELLIPSOID', index=18, number=18,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_MATRIX', index=19, number=19,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_VECTOR', index=20, number=20,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=175,
  serialized_end=668,
)
_sym_db.RegisterEnumDescriptor(_STATETYPE)

StateType = enum_type_wrapper.EnumTypeWrapper(_STATETYPE)
STATE = 0
CARTESIANSTATE = 1
DUALQUATERNIONSTATE = 2
JOINTSTATE = 3
JACOBIANMATRIX = 4
TRAJECTORY = 5
GEOMETRY_SHAPE = 6
GEOMETRY_ELLIPSOID = 7
PARAMETER_DOUBLE = 8
PARAMETER_DOUBLE_ARRAY = 9
PARAMETER_BOOL = 10
PARAMETER_BOOL_ARRAY = 11
PARAMETER_STRING = 12
PARAMETER_STRING_ARRAY = 13
PARAMETER_CARTESIANSTATE = 14
PARAMETER_CARTESIANPOSE = 15
PARAMETER_JOINTSTATE = 16
PARAMETER_JOINTPOSITIONS = 17
PARAMETER_ELLIPSOID = 18
PARAMETER_MATRIX = 19
PARAMETER_VECTOR = 20



_STATE = _descriptor.Descriptor(
  name='State',
  full_name='state_representation.proto.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='state_representation.proto.State.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='state_representation.proto.State.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='empty', full_name='state_representation.proto.State.empty', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='state_representation.proto.State.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=172,
)

_STATE.fields_by_name['type'].enum_type = _STATETYPE
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.enum_types_by_name['StateType'] = _STATETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'state_representation.state_pb2'
  # @@protoc_insertion_point(class_scope:state_representation.proto.State)
  })
_sym_db.RegisterMessage(State)


# @@protoc_insertion_point(module_scope)
