# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state_representation/space/joint/jacobian.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from state_representation import state_pb2 as state__representation_dot_state__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='state_representation/space/joint/jacobian.proto',
  package='state_representation.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/state_representation/space/joint/jacobian.proto\x12\x1astate_representation.proto\x1a state_representation/state.proto\"\xa3\x01\n\x08Jacobian\x12\x30\n\x05state\x18\x01 \x01(\x0b\x32!.state_representation.proto.State\x12\x13\n\x0bjoint_names\x18\x02 \x03(\t\x12\r\n\x05\x66rame\x18\x03 \x01(\t\x12\x17\n\x0freference_frame\x18\x04 \x01(\t\x12\x0c\n\x04rows\x18\x05 \x01(\r\x12\x0c\n\x04\x63ols\x18\x06 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x07 \x03(\x01\x62\x06proto3'
  ,
  dependencies=[state__representation_dot_state__pb2.DESCRIPTOR,])




_JACOBIAN = _descriptor.Descriptor(
  name='Jacobian',
  full_name='state_representation.proto.Jacobian',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='state_representation.proto.Jacobian.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joint_names', full_name='state_representation.proto.Jacobian.joint_names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame', full_name='state_representation.proto.Jacobian.frame', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reference_frame', full_name='state_representation.proto.Jacobian.reference_frame', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rows', full_name='state_representation.proto.Jacobian.rows', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cols', full_name='state_representation.proto.Jacobian.cols', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='state_representation.proto.Jacobian.data', index=6,
      number=7, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=277,
)

_JACOBIAN.fields_by_name['state'].message_type = state__representation_dot_state__pb2._STATE
DESCRIPTOR.message_types_by_name['Jacobian'] = _JACOBIAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Jacobian = _reflection.GeneratedProtocolMessageType('Jacobian', (_message.Message,), {
  'DESCRIPTOR' : _JACOBIAN,
  '__module__' : 'state_representation.space.joint.jacobian_pb2'
  # @@protoc_insertion_point(class_scope:state_representation.proto.Jacobian)
  })
_sym_db.RegisterMessage(Jacobian)


# @@protoc_insertion_point(module_scope)
