# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state_representation/space/joint/joint_state.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from state_representation import state_pb2 as state__representation_dot_state__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='state_representation/space/joint/joint_state.proto',
  package='state_representation.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n2state_representation/space/joint/joint_state.proto\x12\x1astate_representation.proto\x1a state_representation/state.proto\"\xa2\x01\n\nJointState\x12\x30\n\x05state\x18\x01 \x01(\x0b\x32!.state_representation.proto.State\x12\x13\n\x0bjoint_names\x18\x02 \x03(\t\x12\x11\n\tpositions\x18\x03 \x03(\x01\x12\x12\n\nvelocities\x18\x04 \x03(\x01\x12\x15\n\raccelerations\x18\x05 \x03(\x01\x12\x0f\n\x07torques\x18\x06 \x03(\x01\"j\n\x0eJointPositions\x12\x30\n\x05state\x18\x01 \x01(\x0b\x32!.state_representation.proto.State\x12\x13\n\x0bjoint_names\x18\x02 \x03(\t\x12\x11\n\tpositions\x18\x03 \x03(\x01\"l\n\x0fJointVelocities\x12\x30\n\x05state\x18\x01 \x01(\x0b\x32!.state_representation.proto.State\x12\x13\n\x0bjoint_names\x18\x02 \x03(\t\x12\x12\n\nvelocities\x18\x04 \x03(\x01\"f\n\x0cJointTorques\x12\x30\n\x05state\x18\x01 \x01(\x0b\x32!.state_representation.proto.State\x12\x13\n\x0bjoint_names\x18\x02 \x03(\t\x12\x0f\n\x07torques\x18\x06 \x03(\x01\x62\x06proto3'
  ,
  dependencies=[state__representation_dot_state__pb2.DESCRIPTOR,])




_JOINTSTATE = _descriptor.Descriptor(
  name='JointState',
  full_name='state_representation.proto.JointState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='state_representation.proto.JointState.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joint_names', full_name='state_representation.proto.JointState.joint_names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='positions', full_name='state_representation.proto.JointState.positions', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocities', full_name='state_representation.proto.JointState.velocities', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accelerations', full_name='state_representation.proto.JointState.accelerations', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='torques', full_name='state_representation.proto.JointState.torques', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=279,
)


_JOINTPOSITIONS = _descriptor.Descriptor(
  name='JointPositions',
  full_name='state_representation.proto.JointPositions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='state_representation.proto.JointPositions.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joint_names', full_name='state_representation.proto.JointPositions.joint_names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='positions', full_name='state_representation.proto.JointPositions.positions', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=387,
)


_JOINTVELOCITIES = _descriptor.Descriptor(
  name='JointVelocities',
  full_name='state_representation.proto.JointVelocities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='state_representation.proto.JointVelocities.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joint_names', full_name='state_representation.proto.JointVelocities.joint_names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocities', full_name='state_representation.proto.JointVelocities.velocities', index=2,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=497,
)


_JOINTTORQUES = _descriptor.Descriptor(
  name='JointTorques',
  full_name='state_representation.proto.JointTorques',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='state_representation.proto.JointTorques.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joint_names', full_name='state_representation.proto.JointTorques.joint_names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='torques', full_name='state_representation.proto.JointTorques.torques', index=2,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=601,
)

_JOINTSTATE.fields_by_name['state'].message_type = state__representation_dot_state__pb2._STATE
_JOINTPOSITIONS.fields_by_name['state'].message_type = state__representation_dot_state__pb2._STATE
_JOINTVELOCITIES.fields_by_name['state'].message_type = state__representation_dot_state__pb2._STATE
_JOINTTORQUES.fields_by_name['state'].message_type = state__representation_dot_state__pb2._STATE
DESCRIPTOR.message_types_by_name['JointState'] = _JOINTSTATE
DESCRIPTOR.message_types_by_name['JointPositions'] = _JOINTPOSITIONS
DESCRIPTOR.message_types_by_name['JointVelocities'] = _JOINTVELOCITIES
DESCRIPTOR.message_types_by_name['JointTorques'] = _JOINTTORQUES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JointState = _reflection.GeneratedProtocolMessageType('JointState', (_message.Message,), {
  'DESCRIPTOR' : _JOINTSTATE,
  '__module__' : 'state_representation.space.joint.joint_state_pb2'
  # @@protoc_insertion_point(class_scope:state_representation.proto.JointState)
  })
_sym_db.RegisterMessage(JointState)

JointPositions = _reflection.GeneratedProtocolMessageType('JointPositions', (_message.Message,), {
  'DESCRIPTOR' : _JOINTPOSITIONS,
  '__module__' : 'state_representation.space.joint.joint_state_pb2'
  # @@protoc_insertion_point(class_scope:state_representation.proto.JointPositions)
  })
_sym_db.RegisterMessage(JointPositions)

JointVelocities = _reflection.GeneratedProtocolMessageType('JointVelocities', (_message.Message,), {
  'DESCRIPTOR' : _JOINTVELOCITIES,
  '__module__' : 'state_representation.space.joint.joint_state_pb2'
  # @@protoc_insertion_point(class_scope:state_representation.proto.JointVelocities)
  })
_sym_db.RegisterMessage(JointVelocities)

JointTorques = _reflection.GeneratedProtocolMessageType('JointTorques', (_message.Message,), {
  'DESCRIPTOR' : _JOINTTORQUES,
  '__module__' : 'state_representation.space.joint.joint_state_pb2'
  # @@protoc_insertion_point(class_scope:state_representation.proto.JointTorques)
  })
_sym_db.RegisterMessage(JointTorques)


# @@protoc_insertion_point(module_scope)
