var searchData=
[
  ['newdissipative_0',['NewDissipative',['../classcontrollers_1_1impedance_1_1_new_dissipative.html',1,'controllers::impedance::NewDissipative&lt; S &gt;'],['../classcontrollers_1_1impedance_1_1_new_dissipative.html#ad91a9f5dfb7a327b150aec7def697ea9',1,'controllers::impedance::NewDissipative::NewDissipative(const std::list&lt; std::shared_ptr&lt; state_representation::ParameterInterface &gt; &gt; &amp;parameters, const ComputationalSpaceType &amp;computational_space, unsigned int dimensions=6)'],['../classcontrollers_1_1impedance_1_1_new_dissipative.html#adcbaed89bc32acfda0ef7fd8cbdb607b',1,'controllers::impedance::NewDissipative::NewDissipative(const ComputationalSpaceType &amp;computational_space, unsigned int dimensions=6)']]],
  ['newdissipative_3c_20state_5frepresentation_3a_3acartesianstate_20_3e_1',['NewDissipative&lt; state_representation::CartesianState &gt;',['../classcontrollers_1_1impedance_1_1_new_dissipative.html',1,'controllers::impedance']]],
  ['newimpedance_2',['NewImpedance',['../classcontrollers_1_1impedance_1_1_new_impedance.html',1,'controllers::impedance::NewImpedance&lt; S &gt;'],['../classcontrollers_1_1impedance_1_1_new_impedance.html#a66a3d90971a907b7bfa593fa98337cdd',1,'controllers::impedance::NewImpedance::NewImpedance(const std::list&lt; std::shared_ptr&lt; state_representation::ParameterInterface &gt; &gt; &amp;parameters, unsigned int dimensions=6)'],['../classcontrollers_1_1impedance_1_1_new_impedance.html#ad3adfd083c68b2e48aa4f5dabcfb4c42',1,'controllers::impedance::NewImpedance::NewImpedance(unsigned int dimensions=6)']]],
  ['newimpedance_3c_20state_5frepresentation_3a_3acartesianstate_20_3e_3',['NewImpedance&lt; state_representation::CartesianState &gt;',['../classcontrollers_1_1impedance_1_1_new_impedance.html',1,'controllers::impedance']]],
  ['newvelocityimpedance_4',['NewVelocityImpedance',['../classcontrollers_1_1impedance_1_1_new_velocity_impedance.html',1,'controllers::impedance::NewVelocityImpedance&lt; S &gt;'],['../classcontrollers_1_1impedance_1_1_new_velocity_impedance.html#a6bfc7d0b6ef37791edbc7518691dee8b',1,'controllers::impedance::NewVelocityImpedance::NewVelocityImpedance(unsigned int dimensions=6)'],['../classcontrollers_1_1impedance_1_1_new_velocity_impedance.html#a5458688c8cd3dab8bdaf28a539358420',1,'controllers::impedance::NewVelocityImpedance::NewVelocityImpedance(const std::list&lt; std::shared_ptr&lt; state_representation::ParameterInterface &gt; &gt; &amp;parameters, unsigned int dimensions=6)']]],
  ['newvelocityimpedance_3c_20state_5frepresentation_3a_3acartesianstate_20_3e_5',['NewVelocityImpedance&lt; state_representation::CartesianState &gt;',['../classcontrollers_1_1impedance_1_1_new_velocity_impedance.html',1,'controllers::impedance']]],
  ['normalize_6',['normalize',['../classstate__representation_1_1_cartesian_state.html#a4c066e4fdd6a5eda3579ce5ec8e80a01',1,'state_representation::CartesianState']]],
  ['normalized_7',['normalized',['../classstate__representation_1_1_cartesian_acceleration.html#af76a031be54dec17a67995d47db6c4f5',1,'state_representation::CartesianAcceleration::normalized()'],['../classstate__representation_1_1_cartesian_pose.html#abdfdeae5b907866ea949a5c3d62bdfc2',1,'state_representation::CartesianPose::normalized()'],['../classstate__representation_1_1_cartesian_state.html#a5bb2f9b6fd726f2c1d36d4a7dfbf0007',1,'state_representation::CartesianState::normalized()'],['../classstate__representation_1_1_cartesian_twist.html#ad5638298b6ea67ab430f4f8cb8533696',1,'state_representation::CartesianTwist::normalized()'],['../classstate__representation_1_1_cartesian_wrench.html#a356f382caa1b1fbf3fd01908db02e8e4',1,'state_representation::CartesianWrench::normalized(const CartesianStateVariable &amp;state_variable_type=CartesianStateVariable::WRENCH) const']]],
  ['norms_8',['norms',['../classstate__representation_1_1_cartesian_wrench.html#a5584c6d706a3773df0cb292ea78e8af8',1,'state_representation::CartesianWrench::norms()'],['../classstate__representation_1_1_cartesian_twist.html#a3e33c54e1665325e51cf9c73c42fba14',1,'state_representation::CartesianTwist::norms()'],['../classstate__representation_1_1_cartesian_state.html#a4ef6fcae833ef73901d174b4a7e84b76',1,'state_representation::CartesianState::norms()'],['../classstate__representation_1_1_cartesian_pose.html#a4c5b28151f22e6346be702b3d884219d',1,'state_representation::CartesianPose::norms()'],['../classstate__representation_1_1_cartesian_acceleration.html#aca5f7d0c31657d086a10998bb55e0017',1,'state_representation::CartesianAcceleration::norms()']]],
  ['norobotmodelexception_9',['NoRobotModelException',['../classcontrollers_1_1exceptions_1_1_no_robot_model_exception.html',1,'controllers::exceptions']]],
  ['nosolutiontofitexception_10',['NoSolutionToFitException',['../classstate__representation_1_1exceptions_1_1_no_solution_to_fit_exception.html',1,'state_representation::exceptions']]],
  ['notimplementedexception_11',['NotImplementedException',['../classcontrollers_1_1exceptions_1_1_not_implemented_exception.html',1,'controllers::exceptions::NotImplementedException'],['../classdynamical__systems_1_1exceptions_1_1_not_implemented_exception.html',1,'dynamical_systems::exceptions::NotImplementedException'],['../classstate__representation_1_1exceptions_1_1_not_implemented_exception.html',1,'state_representation::exceptions::NotImplementedException']]]
];
