name: 'Build and Push'
description: 'Build the Docker image and push to GitHub Container Registry'
inputs:
  image:
    description: 'The image to build.'
    required: true
    options:
      - 'Development dependencies'
      - 'Protocol dependencies'
  secret:
    description: 'GitHub Container Registry secret'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GitHub Package Registry
      run: echo "${{ inputs.secret }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash

    - name: Build and push image
      run: |
        if [ "${{ inputs.image }}" = "Development dependencies" ]; then
          DOCKERFILE=Dockerfile.base
          IMAGE_NAME=${{ github.repository }}/development-dependencies:latest
        else
          DOCKERFILE=Dockerfile.proto
          IMAGE_NAME=${{ github.repository }}/proto-dependencies
        fi
        docker buildx build --file "${DOCKERFILE}" \
          --platform=linux/arm64,linux/amd64 \
          --push --tag ghcr.io/${IMAGE_NAME} \
          .
      shell: bash
