# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state_representation/geometry/ellipsoid.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from state_representation.geometry import shape_pb2 as state__representation_dot_geometry_dot_shape__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='state_representation/geometry/ellipsoid.proto',
  package='state_representation.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-state_representation/geometry/ellipsoid.proto\x12\x1astate_representation.proto\x1a)state_representation/geometry/shape.proto\"k\n\tEllipsoid\x12\x30\n\x05shape\x18\x01 \x01(\x0b\x32!.state_representation.proto.Shape\x12\x14\n\x0c\x61xis_lengths\x18\x02 \x03(\x01\x12\x16\n\x0erotation_angle\x18\x03 \x01(\x01\x62\x06proto3'
  ,
  dependencies=[state__representation_dot_geometry_dot_shape__pb2.DESCRIPTOR,])




_ELLIPSOID = _descriptor.Descriptor(
  name='Ellipsoid',
  full_name='state_representation.proto.Ellipsoid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='state_representation.proto.Ellipsoid.shape', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='axis_lengths', full_name='state_representation.proto.Ellipsoid.axis_lengths', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotation_angle', full_name='state_representation.proto.Ellipsoid.rotation_angle', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=227,
)

_ELLIPSOID.fields_by_name['shape'].message_type = state__representation_dot_geometry_dot_shape__pb2._SHAPE
DESCRIPTOR.message_types_by_name['Ellipsoid'] = _ELLIPSOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ellipsoid = _reflection.GeneratedProtocolMessageType('Ellipsoid', (_message.Message,), {
  'DESCRIPTOR' : _ELLIPSOID,
  '__module__' : 'state_representation.geometry.ellipsoid_pb2'
  # @@protoc_insertion_point(class_scope:state_representation.proto.Ellipsoid)
  })
_sym_db.RegisterMessage(Ellipsoid)


# @@protoc_insertion_point(module_scope)
