FROM ghcr.io/epfl-lasa/control-libraries/development-dependencies:latest

# Copy and set the entrypoint commands to execute when the container starst
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
