name: Build and Test

# Run workflow on pushes to main and develop branches, on any pull request, or by manual dispatch
on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

# Define the build test jobs for each configuration
jobs:
  build-test-debug:
    runs-on: ubuntu-latest
    name: Debug configuration test
    steps:
      # First check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      # Load the repository build-test action
      - name: Build and Test
        uses: ./.github/actions/build-test
        with:
          configuration: Debug

  build-test-release:
    runs-on: ubuntu-latest
    name: Release configuration test
    steps:
      # First check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      # Load the repository build-test action
      - name: Build and Test
        uses: ./.github/actions/build-test
        with:
          configuration: Release