name: Build and Push

# Run workflow on pushes to main branch or by manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-publish-proto-dependencies:
    runs-on: ubuntu-latest
    name: Build and publish proto dependencies image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build . --file ./Dockerfile.proto  --tag proto-dependencies

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_NAME=${{ github.repository }}/proto-dependencies:latest
          IMAGE_NAME=${IMAGE_NAME/_/-}
          docker tag proto-dependencies ghcr.io/${IMAGE_NAME}
          docker push ghcr.io/${IMAGE_NAME}

  build-publish-development-dependencies:
    needs: build-publish-proto-dependencies
    runs-on: ubuntu-latest
    name: Build and publish development dependencies image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build . --file ./Dockerfile.base  --tag development-dependencies

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_NAME=${{ github.repository }}/development-dependencies:latest
          IMAGE_NAME=${IMAGE_NAME/_/-}
          docker tag development-dependencies ghcr.io/${IMAGE_NAME}
          docker push ghcr.io/${IMAGE_NAME}