name: Build and Push

# Run workflow on pushes to main branch or by manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish-proto-dependencies:
    runs-on: ubuntu-latest
    name: Build and publish proto dependencies image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push
        uses: ./.github/actions/build-push
        with:
          image: "Protocol dependencies"
          secret: ${{ secrets.GITHUB_TOKEN }}

  build-publish-development-dependencies:
    needs: build-publish-proto-dependencies
    runs-on: ubuntu-latest
    name: Build and publish development dependencies image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push
        uses: ./.github/actions/build-push
        with:
          image: "Development dependencies"
          secret: ${{ secrets.GITHUB_TOKEN }}
