name: Build and Push

# Run workflow on pushes to main branch or by manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish-proto-dependencies-focal-fossa:
    runs-on: ubuntu-latest
    name: Build and publish proto dependencies image on ubuntu 20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push
        uses: ./.github/actions/build-push
        with:
          image: "Protocol dependencies"
          base_tag: 20.04
          secret: ${{ secrets.GITHUB_TOKEN }}

  build-publish-proto-dependencies-jammy-jellyfish:
    runs-on: ubuntu-latest
    name: Build and publish proto dependencies image on ubuntu 22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push
        uses: ./.github/actions/build-push
        with:
          image: "Protocol dependencies"
          base_tag: 22.04
          secret: ${{ secrets.GITHUB_TOKEN }}

  build-publish-development-dependencies-focal-fossa:
    needs: build-publish-proto-dependencies-focal-fossa
    runs-on: ubuntu-latest
    name: Build and publish development dependencies image on ubuntu 20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push
        uses: ./.github/actions/build-push
        with:
          image: "Development dependencies"
          base_tag: 20.04
          secret: ${{ secrets.GITHUB_TOKEN }}

  build-publish-development-dependencies-jammy-jellyfish:
    needs: build-publish-proto-dependencies-jammy-jellyfish
    runs-on: ubuntu-latest
    name: Build and publish development dependencies image on ubuntu 22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push
        uses: ./.github/actions/build-push
        with:
          image: "Development dependencies"
          base_tag: 22.04
          secret: ${{ secrets.GITHUB_TOKEN }}
