name: Generate and Deploy Documentation
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Generate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Generate docs
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'doxygen'
          doxyfile-path: 'doxygen.conf'

      - name: Deploy to branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: docs
          publish_dir: ./doxygen/html
          destination_dir: docs